# Generated by Django 5.1.4 on 2025-02-18 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StokeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StokeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nte_price', models.CharField(max_length=250)),
                ('total_price', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=100)),
                ('alert', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('KG', 'કિલોગ્રામ'), ('G', 'ગ્રામ'), ('L', 'લીટર'), ('ML', 'મિલીલીટર'), ('QTY', 'જથ્થો')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stokeitem', to='stockmanagement.stokecategory')),
            ],
        ),
    ]
