# Generated by Django 6.0.2 on 2026-03-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('total_extra_amount', models.DecimalField(decimal_places=0, max_digits=250)),
                ('advance_amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('payment_date', models.DateField()),
                ('transaction_amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('payment_mode', models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('BANK_TRANSFER', 'BANK TRANSFER'), ('ONLINE', 'ONLINE'), ('OTHER', 'OTHER')], default='OTHER', max_length=200)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('payment_status', models.CharField(choices=[('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='eventbooking.eventbooking')),
            ],
        ),
    ]
