# Generated by Django 6.0.2 on 2026-03-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selection_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(default=dict)),
                ('person_count', models.IntegerField(default=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='item.item')),
            ],
        ),
    ]
