# Generated by Django 5.1.4 on 2026-02-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_base_cost_item_selection_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='person_count',
        ),
    ]
