# Generated by Django 5.1.4 on 2026-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_recipeingredient_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='person_count',
            field=models.IntegerField(default=100),
        ),
    ]
