# Generated by Django 5.1.4 on 2026-02-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_recipeingredient_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_vendor_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
