# Generated by Django 5.1.4 on 2026-02-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_is_vendor_item_item_vendor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_vendor_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendor_price',
        ),
    ]
