# Generated by Django 5.1.4 on 2026-02-24 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=17)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=50)),
                ('advance_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('advance_payment_mode', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('BANK_TRANSFER', 'BANK TRANSFER'), ('ONLINE', 'ONLINE'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=20)),
                ('extra_service_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('extra_service', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=100)),
                ('event_address', models.TextField(blank=True)),
                ('per_dish_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_persons', models.CharField(blank=True, max_length=150, null=True)),
                ('selected_items', models.JSONField(default=dict)),
                ('extra_service_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('extra_service', models.JSONField(default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eventbooking.eventbooking')),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
