# Generated by Django 5.1.4 on 2026-02-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='extra_service',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='extra_service_amount',
        ),
    ]
