# Generated by Django 5.1.4 on 2025-02-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StokeCategory',
        ),
    ]
