# Generated by Django 6.0.2 on 2026-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0002_remove_eventbooking_extra_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='assigned_vendors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
