# Generated by Django 5.1.4 on 2025-03-19 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0002_delete_stokecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='mobile_no',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+91 9999999999'.", regex='^\\+\\d{2}\\s\\d{10}$')]),
        ),
    ]
