# Generated by Django 5.1.4 on 2025-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0004_alter_eventbooking_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='note_status',
            field=models.BooleanField(default=False),
        ),
    ]
