# Generated by Django 5.1.4 on 2025-04-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0005_eventbooking_note_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='note_status',
            new_name='rule',
        ),
    ]
