# Generated by Django 5.1.4 on 2026-02-24 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0006_rename_note_status_eventbooking_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbooking',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='estimated_persons',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_address',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='per_dish_amount',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='selected_items',
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=100)),
                ('event_address', models.TextField(blank=True)),
                ('per_dish_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_persons', models.CharField(blank=True, max_length=150, null=True)),
                ('selected_items', models.JSONField(default=dict)),
                ('extra_service_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('extra_service', models.JSONField(default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eventbooking.eventbooking')),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
