# Generated by Django 6.0.2 on 2026-03-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventIngridientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('ingridient_list_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IngridientsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('positions', models.IntegerField(default=0)),
                ('is_common', models.BooleanField(default=False, help_text='Always include items from this category in all event orders')),
            ],
        ),
        migrations.CreateModel(
            name='IngridientsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ListOfIngridients.ingridientscategory')),
            ],
        ),
    ]
