# Generated by Django 5.1.4 on 2025-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfIngridients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIngridientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('ingridient_list_data', models.JSONField(default=dict)),
            ],
        ),
    ]
