# Generated by Django 5.1.4 on 2026-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfIngridients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridientscategory',
            name='is_common',
            field=models.BooleanField(default=False, help_text='Always include items from this category in all event orders'),
        ),
    ]
