# Generated by Django 6.0.2 on 2026-03-05 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caters_name', models.CharField(max_length=255, verbose_name='Caters Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('fssai_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='FSSAI Number')),
                ('godown_address', models.TextField(blank=True, null=True, verbose_name='Godown Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'db_table': 'BusinessProfile',
            },
        ),
    ]
