# Generated by Django 6.0.2 on 2026-03-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_businessprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='user',
        ),
    ]
