# Generated by Django 6.0.2 on 2026-03-05 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Role Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Staff Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('staff_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Agency', 'Agency'), ('Contract', 'Contract')], default='Contract', max_length=20, verbose_name='Staff Type')),
                ('fixed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed Salary')),
                ('per_person_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Per Person (Rate)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventstaff.staffrole', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Total Days')),
                ('number_of_persons', models.PositiveIntegerField(default=1, help_text='Number of staff members supplied by agency/contractor', verbose_name='Number of Persons')),
                ('per_person_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use staff's default rate", max_digits=10, null=True, verbose_name='Per Person Rate (Override)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Remaining Amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', editable=False, max_length=20, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='eventbooking.eventsession', verbose_name='Session')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='eventstaff.staff', verbose_name='Staff')),
                ('role_at_event', models.ForeignKey(blank=True, help_text='Override default role for this specific event if needed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventstaff.staffrole', verbose_name='Role at Event')),
            ],
            options={
                'verbose_name': 'Event Staff Assignment',
                'verbose_name_plural': 'Event Staff Assignments',
                'unique_together': {('session', 'staff')},
            },
        ),
    ]
