# Generated by Django 5.1.4 on 2026-03-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventbooking', '0002_remove_eventbooking_extra_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Staff Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('Labor', 'Labor'), ('Waiter', 'Waiter')], default='Labor', max_length=20, verbose_name='Role')),
                ('staff_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Agency', 'Agency'), ('Contract', 'Contract')], default='Contract', max_length=20, verbose_name='Staff Type')),
                ('agency_name', models.CharField(blank=True, help_text='Required if staff type is Agency', max_length=150, null=True, verbose_name='Agency Name')),
                ('contract_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contract Rate')),
                ('fixed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed Salary')),
                ('per_day_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Default Per Day Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_event', models.CharField(blank=True, help_text='Override default role for this specific event if needed', max_length=50, verbose_name='Role at Event')),
                ('total_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Total Days')),
                ('per_day_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use staff's default rate", max_digits=10, null=True, verbose_name='Per Day Rate (Override)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Remaining Amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', editable=False, max_length=20, verbose_name='Payment Status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='eventbooking.eventbooking', verbose_name='Event')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='eventstaff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Event Staff Assignment',
                'verbose_name_plural': 'Event Staff Assignments',
                'unique_together': {('event', 'staff')},
            },
        ),
    ]
