# Generated by Django 6.0.2 on 2026-03-02 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def convert_roles(apps, schema_editor):
    StaffRole = apps.get_model("eventstaff", "StaffRole")
    Staff = apps.get_model("eventstaff", "Staff")
    EventStaffAssignment = apps.get_model("eventstaff", "EventStaffAssignment")

    for staff in Staff.objects.all():
        role_obj, _ = StaffRole.objects.get_or_create(
            name=staff.role if staff.role else "Labor"
        )
        staff.role_new = role_obj
        staff.save()

    for assignment in EventStaffAssignment.objects.all():
        if assignment.role_at_event:
            role_obj, _ = StaffRole.objects.get_or_create(name=assignment.role_at_event)
            assignment.role_at_event_new = role_obj
            assignment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("eventstaff", "0002_eventstaffassignment_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Role Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Role Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Role",
                "verbose_name_plural": "Staff Roles",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="role_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="eventstaff.staffrole",
            ),
        ),
        migrations.AddField(
            model_name="eventstaffassignment",
            name="role_at_event_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eventstaff.staffrole",
            ),
        ),
        migrations.RunPython(convert_roles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="staff",
            name="role",
        ),
        migrations.RemoveField(
            model_name="eventstaffassignment",
            name="role_at_event",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="role_new",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="eventstaffassignment",
            old_name="role_at_event_new",
            new_name="role_at_event",
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="eventstaff.staffrole",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="eventstaffassignment",
            name="role_at_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Override default role for this specific event if needed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eventstaff.staffrole",
                verbose_name="Role at Event",
            ),
        ),
    ]
