# Generated by Django 6.0.2 on 2026-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstaff', '0003_staffrole_alter_eventstaffassignment_role_at_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstaffassignment',
            name='per_day_rate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contract_rate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='per_day_rate',
        ),
        migrations.AddField(
            model_name='eventstaffassignment',
            name='per_person_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use staff's default rate", max_digits=10, null=True, verbose_name='Per Person Rate (Override)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='per_person_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Per Person (Rate)'),
        ),
    ]
