# Generated by Django 6.0.2 on 2026-03-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventbooking", "0002_remove_eventbooking_extra_service_and_more"),
        ("eventstaff", "0004_remove_eventstaffassignment_per_day_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventstaffassignment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_assignments",
                to="eventbooking.eventsession",
                verbose_name="Session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventstaffassignment",
            unique_together={("session", "staff")},
        ),
        migrations.RemoveField(
            model_name="eventstaffassignment",
            name="event",
        ),
    ]
