# Generated by Django 6.0.2 on 2026-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstaff', '0005_alter_eventstaffassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaffassignment',
            name='number_of_persons',
            field=models.PositiveIntegerField(default=1, help_text='Number of staff members supplied by agency/contractor', verbose_name='Number of Persons'),
        ),
    ]
